### ISSUE TITLE
Reuse the socket instance

### ISSUE THREAD

**Issue by eric** [sc0ttkclark/papertrail#1]
At a higher load, calling [`socket_create( AF_INET, SOCK_DGRAM, SOL_UDP )`](https://github.com/sc0ttkclark/papertrail/blob/de4f90dac2c1341ace54a5d5778e9a4212e9e342/papertrail.php#L62) for each log message will become expensive.

It would perform better to only create one socket (in a constructor, for instance) and reuse it for all log calls.

**Comment by sc0ttkclark** [comment]
Thanks @eric, I went ahead and did that.
