### ISSUE TITLE
Logging all PHP errors

### ISSUE THREAD

**Issue by tdmalone** [sc0ttkclark/papertrail#2]
Thanks for putting this together!

More a question than anything else, just to check whether I'm barking up the wrong tree, if I wanted to send all PHP errors to Papertrail (and can't use the usual remote_syslog option because it's shared hosting), I would imagine I could use `set_error_handler()` and send errors through to `WP_Papertrail_API::log()`... right?

Would you suggest doing this any differently?

**Comment by sc0ttkclark** [comment]
I just pushed up the code I was using for this. Try setting `define( 'WP_PAPERTRAIL_ERROR_HANDLER', true );` in your wp-config.php to log all errors to Papertrail. Heads up -- it can really bog things down in your Papertrail so be ready to hit some limits if you don't have a beefy plan on Papertrail and you've got a potentially 'noisy' codebase. :)

**Comment by tdmalone** [comment]
Thanks so much @sc0ttkclark - that's even better than I expected!!
